version: '3.7'

services:
    web:
        build: ./
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/code
        ports:
        - 8000:8000
        env_file:
        - ./env/.env.dev
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=merlin
        - POSTGRES_PASSWORD=merlin_pass
        - POSTGRES_DB=merlin_dev

volumes:
    postgres_data: