version: '3.7'

volumes:
  local_postgres_data: {}

services:
  web:
    build: 
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - /usr/src/app/
    ports:
    - 8000:8000
    env_file:
    - ./env/.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
    - local_postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=merlin
    - POSTGRES_PASSWORD=merlin
    - POSTGRES_DB=merlin_dev
  redis:
    image: redis:5-alpine
  celery_worker:
    build: 
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: merlin_celery_celery_worker
    command: celery -A merlin worker -l INFO
    volumes:
      - /usr/src/app/
    env_file:
      - ./env/.env.dev
    depends_on:
      - redis
      - db
      - web

  celery_beat:
    build: 
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: merlin_celery_celery_beat
    command: celery -A merlin beat -l INFO
    volumes:
      - /usr/src/app/
    env_file:
      - ./env/.env.dev
    depends_on:
      - redis
      - db
      - web
  flower:
    image: mher/flower
    volumes:
      - /usr/src/app/
    env_file:
      - ./env/.env.dev
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
      - web 
      - celery_beat
      - celery_worker

